app:
  host: <%= process.env.HOST %>
  node_env: <%= process.env.NODE_ENV %>
  port: <%= process.env.PORT %>
  sentry:
    host: <%= process.env.SENTRY_HOST %>
    enabled: <%= process.env.SENTRY_ENABLED %>
